---
all:
  hosts:
   urk_prd:
      ansible_host: 10.244.0.71
   sabewa_prd:
      ansible_host: 10.244.0.70
   breda_prd:
      ansible_host: 10.244.0.66
    # Test host die niet bestaat  
    #beek_prd: 
      #ansible_host: 10.244.0.100 
    # Voeg hier meer hosts toe

